name: Coverage
on: push
jobs:
  coverage:
    name: Coverage
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-nox.yaml@main
    with:
      python_version: '3.9'
      python_architecture: x64
      sessions: tests-3.9
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
