name: Release
on:
  release:
    types: [published]
jobs:
  release:
    uses: Informasjonsforvaltning/workflows/.github/workflows/release-poetry.yaml@main
    with:
      python_version: '3.9'
      python_architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
