name: TestPyPI
on:
  push:
    branches:
      - main
jobs:
  test_pypi:
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-pypi.yaml@main
    with:
      python_version: '3.9'
      python_architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
